### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/scratchaddons.github.io#1]
There's this and then another repo called 'website' so what's this for?

**Comment by Hans5958** [comment]
Oh, sorry for not explaining, this is done so https://scratchaddons.github.io visitors got redirected to https://scratchaddons.com.

**Comment by Explosion-Scratch** [comment]
> Oh, sorry for not explaining, this is done so https://scratchaddons.github.io visitors got redirected to https://scratchaddons.com.

Okay! lol Nice!
