### ISSUE TITLE
New header?

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/scratchaddons.github.io#18]
What do you guys think of this header instead:
https://Header-test.explosionscratc.repl.co

**Comment by Explosion-Scratch** [comment]
Try resizing the window too.

**Comment by YOYITsM3M8** [comment]
On mobile the "hamburger menu" is in a weird spot other than that good

**Comment by Explosion-Scratch** [comment]
> On mobile the "hamburger menu" is in a weird spot other than that good

Cool! Thanks! :)

**Comment by YOYITsM3M8** [comment]
Also, plez add a dark theme! Ps exchange the icon for a dark mode version

**Comment by Explosion-Scratch** [comment]
Okay! I'm on mobile now but I'll work on re-doing it for dark mode. Eventually I'll re-make the actual site with the styles I'm working on now. Right now I'm going to work on making a dark and light theme and finishing the themes coding.

**Comment by GrahamSH-LLK** [comment]
Can you please change it so that it matches the Settings page of the extension?

**Comment by Explosion-Scratch** [comment]
Hmm, I'll see what I can do with dark mode first and then I might try implementing that color scheme.

**Comment by GrahamSH-LLK** [comment]
Close this.

**Comment by Explosion-Scratch** [comment]
> Close this.

Thanks for reminding me! I just did!
