### ISSUE TITLE
[Announcement] I'm replacing the old website with my new one that I've been working on.

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/scratchaddons.github.io#22]
I have replaced the old ScratchAddons with the new version that I have been working on. The old website is attached in a zip file just in case. 
[Old ScratchAddons website archive.zip](https://github.com/ScratchAddons/scratchaddons.github.io/files/5188940/Old.ScratchAddons.website.archive.zip)

**Comment by YOYITsM3M8** [comment]
404 on contribute

**Comment by JeffaloBob** [comment]
i like

**Comment by BoomerScratch** [comment]
Did you know you can view the history by commit? <sub>[Here is the proof if you want it](https://github.com/ScratchAddons/scratchaddons.github.io/tree/5d8f72055b108a243f6162553e8281da6ed40a30)</sub>

**Comment by JeffaloBob** [comment]
woah, can i clone it like that as well?

**Comment by BoomerScratch** [comment]
@JeffaloBob Yes (if I remember correctly):
```bash
git clone https://github.com/ScratchAddons/scratchaddons.github.io 5d8f72055b108a243f6162553e8281da6ed40a30
```

**Comment by Explosion-Scratch** [comment]
> 404 on contribute

I know. I'm still working on it! :)

**Comment by Explosion-Scratch** [comment]
> i like

Thanks! :) 👍

**Comment by Explosion-Scratch** [comment]
> Did you know you can view the history by commit? [Here is the proof if you want it](https://github.com/ScratchAddons/scratchaddons.github.io/tree/5d8f72055b108a243f6162553e8281da6ed40a30)

Noice.

**Comment by GrahamSH-LLK** [comment]
Un-pin it!
