### ISSUE TITLE
Remove .html

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/scratchaddons.github.io#23]
GHPages creates a copy of the page without the .html, which is cleaner. I'll create a pr fixing this.

**Comment by Explosion-Scratch** [comment]
What does this do? Does it remove ".html" from the page names?

**Comment by GrahamSH-LLK** [comment]
> What does this do? Does it remove ".html" from the page names?

There are 2 copies of each page. For example, you can go to /about.html, or /about. It is much cleaner and more professional to skip the .HTML. This PR removes the .html from the a elements, but the .html pages can still be accessed.

**Comment by Explosion-Scratch** [comment]
> > What does this do? Does it remove ".html" from the page names?
> 
> There are 2 copies of each page. For example, you can go to /about.html, or /about. It is much cleaner and more professional to skip the .HTML. This PR removes the .html from the a elements, but the .html pages can still be accessed.

Okay! Thanks! :) I'll merge it!

**Comment by GrahamSH-LLK** [comment]
@Explosion-Scratch There is one more link that I missed on index.html. I fixed it in #27
