### ISSUE TITLE
It's Scratch Addons with a space!

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/scratchaddons.github.io#32]
not ScratchAddons, as what @WorldLanguages said

**Comment by Explosion-Scratch** [comment]
Can you give me a quote from WL? It's gonna be quite a bit to change lol

**Comment by Hans5958** [comment]
Search on Discord. I can't because I'm not on my computer rn.

**Comment by WorldLanguages** [comment]
With space.

**Comment by Explosion-Scratch** [comment]
I'm not allowed to use discord @Hans5958, also thanks @WorldLanguages. I'll fix it tomorrow.

**Comment by Hans5958** [comment]
Oh, apologizes. I thought you actually have free access on any websites ever. Thank god WL said it here.

**Comment by Explosion-Scratch** [comment]
lol it's fine
