### ISSUE TITLE
I need access.

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/scratchaddons.github.io#8]
I need access to commit directly to this, it says 'access requested'. I'm using repl.it to edit the code. For now I'm having to constantly create a fork and then delete it once it has been merged and then re-create it so that it dosen't get behind on the commits from other things, like YOYITsM3M8's help.

**Comment by YOYITsM3M8** [comment]
make branches

**Comment by YOYITsM3M8** [comment]
ask w_l

**Comment by YOYITsM3M8** [comment]
also me too

**Comment by Explosion-Scratch** [comment]
> make branches

That's what I've been doing.

**Comment by YOYITsM3M8** [comment]
@WorldLanguages ^^^

**Comment by WorldLanguages** [comment]
Looks like you're a repo admin already - someone else might have added it to you (maybe Apple or Ucrash?)

**Comment by YOYITsM3M8** [comment]
> Looks like you're a repo admin already - someone else might have added it to you (maybe Apple or Ucrash?)

Add me to repo

**Comment by Explosion-Scratch** [comment]
> Looks like you're a repo admin already - someone else might have added it to you (maybe Apple or Ucrash?)

Okay! Thanks! :)

**Comment by Explosion-Scratch** [comment]
Hmm, I just checked, I seem to have write access to this (I can merge stuff) but I can't seem to connect repl.it to this. I guess I'll just have to use branches for now.
I click "add/remove repos" here:
![image](https://user-images.githubusercontent.com/61319150/92285996-5fb9b800-eecb-11ea-9ba4-efb40859ea02.png)
And then it goes to here:
![image](https://user-images.githubusercontent.com/61319150/92285953-46187080-eecb-11ea-93ea-b053bdd1c87c.png)

**Comment by WorldLanguages** [comment]
Try now

**Comment by Explosion-Scratch** [comment]
> Try now

Hmm, okay =/

**Comment by Explosion-Scratch** [comment]
Works now! Thanks! :)
